/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */
drop database if exists test_db;
create database if not exists test_db;
use test_db;
DROP TABLE IF EXISTS `Person`;

CREATE TABLE `Person` (
  `id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `age` SMALLINT UNSIGNED NOT NULL,
  `name` TEXT NOT NULL,
  `update` TIMESTAMP NOT NULL)
 ENGINE=InnoDB;

